version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      mantine:
        patterns:
          - "@mantine/*"
      everything-else:
        patterns:
          - "*"
