name: PR Linting

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 26
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint

      - name: Typescript
        run: npm run typecheck
