name: PR Tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-tests

permissions:
  contents: read
  pull-requests: write

jobs:
  setup:
    name: setup
    outputs:
      branch: ${{ steps.branch_name.outputs.current_branch }}
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch_name
        uses: tj-actions/branch-names@v8

  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Create Neon Branch
        id: create-branch
        uses: neondatabase/create-branch-action@v6
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch_name: preview/pr-${{ github.event.number }}-${{ needs.setup.outputs.branch }}-tests
          api_key: ${{ secrets.NEON_API_KEY }}
          database: watchrr

      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=${{ steps.create-branch.outputs.db_url_pooled }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 25
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Migrations
        run: npm run db:migrate

      - name: Post Schema Diff to PR
        uses: neondatabase/schema-diff-action@v1
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          compare_branch: preview/pr-${{ github.event.number }}-${{ needs.setup.outputs.branch }}-tests
          api_key: ${{ secrets.NEON_API_KEY }}
          database: watchrr

      - name: Test
        run: npm run test:coverage

      - name: Post coverage comment
        if: success()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-path: coverage/coverage-summary.json
